import 'package:flutter/material.dart';

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFFFFFFFF),
  onPrimary: Color(0xFF000000),
  primaryContainer: Color(0xFFD7E2FF),
  onPrimaryContainer: Color(0xFF001B3F),
  secondary: Color(0xFF6A46C1),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFE9DDFF),
  onSecondaryContainer: Color(0xFF22005C),
  tertiary: Color(0xFF705574),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFFAD8FC),
  onTertiaryContainer: Color(0xFF29132E),
  error: Color(0xFFBA1A1A),
  errorContainer: Color(0xFFFFDAD6),
  onError: Color(0xFFFFFFFF),
  onErrorContainer: Color(0xFF410002),
  background: Color(0xFFFFFFFF),
  onBackground: Color(0xFF000000),
  surface: Color(0xFFFFFFFF),
  onSurface: Color(0xFF000000),
  surfaceVariant: Colors.yellow,
  onSurfaceVariant: Color(0xFF000000),
  outline: Color(0xFF74777F),
  onInverseSurface: Color(0xFFEAF1FF),
  inverseSurface: Color(0xFF00325B),
  inversePrimary: Color(0xFFABC7FF),
  shadow: Color(0xFF74777F),
  surfaceTint: Color(0xFF195CB5),
);
